directories:
  output: release
  buildResources: build
appId: com.possiblypengu.cereal
productName: Cereal
copyright: Copyright © 2026 PossiblyPengu
files:
  - filter:
      - dist/**
      - dist-electron/**
      - '!dist-electron/resources/chiaki-ng/**'
      - node_modules/**
      - package.json
extraResources:
  - from: dist-electron/resources/chiaki-ng
    to: chiaki-ng
    filter:
      - '**/*'
asar: true
win:
  target:
    - target: nsis
      arch:
        - x64
  artifactName: Cereal-Setup-${version}.exe
  icon: build/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerHeaderIcon: build/icon.ico
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Cereal
publish:
  provider: github
  owner: PossiblyPengu
  repo: CEREAL
  releaseType: release
electronVersion: 41.1.1
